### ISSUE TITLE
UnboundLocalError: local variable 'rbox' referenced before assignment

### ISSUE THREAD

**Issue by ulyduts** [Egrt/yolov7-obb#11]
你好，请问数据加载阶段这部分报错怎么解决呢？
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Anaconda3\envs\python37\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Anaconda3\envs\python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Anaconda3\envs\python37\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\hb\yolov7-tiny-obb-master\utils\dataloader.py", line 55, in __getitem__
    image, rbox      = self.get_random_data(self.annotation_lines[index], self.input_shape, random = self.train)
  File "D:\hb\yolov7-tiny-obb-master\utils\dataloader.py", line 210, in get_random_data
    return image_data, rbox
UnboundLocalError: local variable 'rbox' referenced before assignment

**Comment by Egrt** [comment]
> 

检查数据集的加载，生成的train.txt格式是否正确。

**Comment by yanhaoerer** [comment]
train.txt应当为什么样子呢？

**Comment by hecheng000** [comment]
> 

train.txt是正确的啊 还是报上述错误

**Comment by hecheng000** [comment]
> 你好，请问数据加载阶段这部分报错怎么解决呢？ UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 0. Original Traceback (most recent call last): File "D:\Anaconda3\envs\python37\lib\site-packages\torch\utils\data_utils\worker.py", line 287, in _worker_loop data = fetcher.fetch(index) File "D:\Anaconda3\envs\python37\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\Anaconda3\envs\python37\lib\site-packages\torch\utils\data_utils\fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\hb\yolov7-tiny-obb-master\utils\dataloader.py", line 55, in **getitem** image, rbox = self.get_random_data(self.annotation_lines[index], self.input_shape, random = self.train) File "D:\hb\yolov7-tiny-obb-master\utils\dataloader.py", line 210, in get_random_data return image_data, rbox UnboundLocalError: local variable 'rbox' referenced before assignment

请问你解决了吗 跟你同样错误

**Comment by liyansong123** [comment]
你好，请问解决了吗，自己的数据集也是这样的原因
Epoch 1/300:   0%|          | 5/1049 [00:15<29:12,  1.68s/it, loss=3.35, lr=0.0003]Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\codes\yolov7-obb-master\train.py", line 552, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "C:\Users\Administrator\Desktop\codes\yolov7-obb-master\utils\utils_fit.py", line 16, in fit_one_epoch
    for iteration, batch in enumerate(gen):
  File "E:\Anaconda3\envs\gz_envs\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "E:\Anaconda3\envs\gz_envs\lib\site-packages\torch\utils\data\dataloader.py", line 1065, in _next_data
    return self._process_data(data)
  File "E:\Anaconda3\envs\gz_envs\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "E:\Anaconda3\envs\gz_envs\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
UnboundLocalError: Caught UnboundLocalError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "E:\Anaconda3\envs\gz_envs\lib\site-packages\torch\utils\data\_utils\worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "E:\Anaconda3\envs\gz_envs\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "E:\Anaconda3\envs\gz_envs\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\Administrator\Desktop\codes\yolov7-obb-master\utils\dataloader.py", line 55, in __getitem__
    image, rbox      = self.get_random_data(self.annotation_lines[index], self.input_shape, random = self.train)
  File "C:\Users\Administrator\Desktop\codes\yolov7-obb-master\utils\dataloader.py", line 210, in get_random_data
    return image_data, rbox
UnboundLocalError: local variable 'rbox' referenced before assignment

**Comment by liyansong123** [comment]
讲数据集中空标签删掉即可，建议删掉txt空标签后转为xml，txt为空的标签大小都是0

**Comment by XSC199721** [comment]
在对应的出错位置设置rbox=[]就好了

**Comment by shallwing** [comment]
我也出现过这个问题，我解决的方案是，定位到相应的数据集图片，把它删了就行，少了一张训练集图片没有太大问题
