### ISSUE TITLE
训练自己的数据集时，在Calculate map步骤发生“ValueError: could not convert string to float: 'Pkw'”，PKW是我训练集的一个标签，数据集格式正确。请问如何解决

### ISSUE THREAD

**Issue by MuBuZe** [Egrt/yolov7-obb#22]
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "/home/sja/yolov7-obb-master/utils/utils_fit.py", line 104, in fit_one_epoch
    eval_callback.on_epoch_end(epoch + 1, model_train_eval)
  File "/home/sja/yolov7-obb-master/utils/callbacks.py", line 225, in on_epoch_end
    temp_map = get_map(self.MINOVERLAP, False, path = self.map_out_path)
  File "/home/sja/yolov7-obb-master/utils/utils_map.py", line 438, in get_map
    bounding_boxes.sort(key=lambda x:float(x['confidence']), reverse=True)
  File "/home/sja/yolov7-obb-master/utils/utils_map.py", line 438, in <lambda>
    bounding_boxes.sort(key=lambda x:float(x['confidence']), reverse=True)
ValueError: could not convert string to float: 'Pkw'

**Comment by MuBuZe** [comment]
没事了 解决了  少安装一个包，但还是谢谢博主

**Comment by XSC199721** [comment]
我也遇到了这个问题，兄弟咋解决呀

**Comment by XSC199721** [comment]
> 我也遇到了这个问题，兄弟咋解决呀

看了会代码，我也解决了，哈哈哈，谢谢兄弟

**Comment by yaosx425** [comment]
> > 我也遇到了这个问题，兄弟咋解决呀
> 
> 看了会代码，我也解决了，哈哈哈，谢谢兄弟
怎么解决的兄弟 我也遇到了
