### ISSUE TITLE
独热编码出错

### ISSUE THREAD

**Issue by fromchina-nb** [Egrt/yolov7-obb#25]
我用的dota数据做了一下训练，但是每次到独热编码那一块就会报错为RuntimeError: Class values must be smaller than num_classes.

**Comment by fromchina-nb** [comment]
Traceback (most recent call last):
  File "train.py", line 552, in <module>
    fit_one_epoch(model_train, model, ema, yolo_loss, loss_history, eval_callback, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, fp16, scaler, save_period, save_dir, local_rank)
  File "/root/yolov7obb/utils/utils_fit.py", line 34, in fit_one_epoch
    loss_value      = yolo_loss(outputs, targets, images)
  File "/root/yolov7obb/nets/yolo_training.py", line 104, in __call__
    bs, as_, gjs, gis, targets, anchors = self.build_targets(predictions, targets, imgs)
  File "/root/yolov7obb/nets/yolo_training.py", line 346, in build_targets
    gt_cls_per_image = F.one_hot(this_target[:, 1].to(torch.int64), self.num_classes).float().unsqueeze(1).repeat(1, pxyxys.shape[0], 1)
RuntimeError: Class values must be smaller than num_classes.
报错是这个
